feat: chap17
Road-of-CODEr/modern-js-deepdive pull request #1
Opened 2021-04-29 15:18 UTC by hayoung0Lee

생성자 함수 부분 정리했습니다.

2021-04-30 12:30 UTC, 1ilsang requested changes
고생하셨습니다. 아래 내용 확인해주세요~

2021-04-30 12:30 UTC, 1ilsang commented on [17] 생성자 함수에 의한 객체 생성/README.md
> +생성자 함수는 객체를 생성하는 템플릿처럼 이런 생성자 함수를 통해서 프로퍼티 구조가 동일한 인스턴스를 쉽게 반복적으로 생성할 수 잇따.
잇따

2021-04-30 12:30 UTC, 1ilsang commented on [17] 생성자 함수에 의한 객체 생성/README.md
> +아래는 객체 리터럴 방식을 통해서 객체를 생성하는 경우인데, 이때 동일한 프로퍼티를 가진 객체를 여러개 생성할 때 같은 객체 리터럴 방식으로 프로퍼티를 기술해야하는 점이 비효율 적이다. 또한 state와 같은 프로퍼티는 객체마다 다를 수 있지만 `getState`와 같은 메서드는 내용이 공통인 경우가 있는데, 이런 메소드 선언이 반복되는 것이 문제가 될
> 객체 리터럴 방식으로 프로퍼티를 기술해야하는 점이 비효율 적이다.
>
> 이런 메소드 선언이 반복되는 것이 문제가 될 수 있다.

각 상황에 맞는 예시코드가 있으면 더 좋을것 같아요!

2021-04-30 12:30 UTC, 1ilsang commented on [17] 생성자 함수에 의한 객체 생성/README.md
> +        return new func();
`func1` 이라고 해주어야 하겠네요.

2021-04-30 12:30 UTC, 1ilsang commented on [17] 생성자 함수에 의한 객체 생성/README.md
> +이를 통해서 생성자로 호출 되지 않은 경우에도 인스턴스를 생성해서 반환한다. 되지
되지..?

2021-07-08 00:10 UTC, hayoung0Lee commented on [17] 생성자 함수에 의한 객체 생성/README.md
> +생성자 함수는 객체를 생성하는 템플릿처럼 이런 생성자 함수를 통해서 프로퍼티 구조가 동일한 인스턴스를 쉽게 반복적으로 생성할 수 잇따.
이제 발견함옄ㅋㅋㅋㅋㅋ 고칠게요!!

2026-04-16 05:20 UTC, closed without merging